spring:
  application:
    name: "match-completion-service"
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: match-completed-consumer-group
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.tough.matchcompletionservice.model
        spring.json.value.default.type: com.tough.matchcompletionservice.model.MatchState
      auto-offset-reset: earliest
server:
  port: 8080