services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network

  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    env_file: ./authentication/environment-variables/.env
    ports:
      - "8081:8080"
    volumes:
      - sqlite-data:/data
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:
  sqlite-data:

networks:
  app-network:
    driver: bridge